import {useEffect,useRef,useState} from 'react'
import type {ArticleCategory} from '../../data'
import type {PublicArticle} from '../articles/article.model'
import type {DraftSnapshot} from '../../shared/contracts/forms'
import {canPublish} from '../../shared/contracts/forms'
import {useLocale,localeOrder,type Locale} from '../../shared/i18n'
import {Field,TextArea} from '../../design/Field'
import {Dialog} from '../../design/Dialog'
import {Icon} from '../../design/Icon'
import {useNavigationGuard} from '../../app/router'
import {errorKey} from '../../shared/api'
import {MediaPanel} from './MediaPanel'
import {articleToSnapshot,emptySnapshot,isDraftDirty,makeSlug,buildSaveInput,type DraftRecord} from './editorial.model'
import {saveDraft,publishDraft} from './editorial.api'
export function DraftEditor({article,initial,categories,onClose,onPublished}:{article:PublicArticle|null;initial:DraftRecord|null;categories:ArticleCategory[];onClose:()=>void;onPublished:()=>void}){
 const {t,locale}=useLocale(),id=useRef(initial?.id||crypto.randomUUID()),[record,setRecord]=useState<DraftRecord|null>(initial),[value,setValue]=useState<DraftSnapshot>(()=>initial?.snapshot||(article?articleToSnapshot(article):emptySnapshot())),[saved,setSaved]=useState<DraftSnapshot>(()=>initial?.snapshot||(article?articleToSnapshot(article):emptySnapshot())),[editLocale,setEditLocale]=useState<Locale>(locale),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[validVideo,setValidVideo]=useState(true),[preview,setPreview]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[slugEdited,setSlugEdited]=useState(Boolean(initial?.snapshot.slug||article?.slug)),saveReceipt=useRef<{body:string;id:string}|null>(null),publishReceipt=useRef<{body:string;id:string}|null>(null)
 const dirty=isDraftDirty(value,saved),locked=busy||uploading
 useNavigationGuard(dirty||uploading,t('unsaved'))
 useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(dirty||uploading){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler)},[dirty,uploading])
 const close=()=>{if(!locked&&(!dirty||window.confirm(t('unsaved'))))onClose()}
 const save=async():Promise<DraftRecord>=>{const currentArticle=record?.articleId?{id:record.articleId,updated_at:record.baseUpdatedAt!}:article;const payload=buildSaveInput(id.current,record?.revision||0,currentArticle,value);const body=JSON.stringify(payload);if(saveReceipt.current?.body!==body)saveReceipt.current={body,id:crypto.randomUUID()};const result=await saveDraft(payload,saveReceipt.current.id);setRecord(result);setSaved(result.snapshot);setValue(result.snapshot);return result}
 const persist=async(publish:boolean)=>{
  if(locked||!validVideo)return;setError('');setNotice('')
  if(publish&&!canPublish(value)){setError('publishNeedsContent');return}
  if(publish&&!window.confirm(t('publishConfirm')))return
  setBusy(true)
  try{const draft=await save();setNotice('draftSaved');if(publish){const body=JSON.stringify({id:draft.id,revision:draft.revision});if(publishReceipt.current?.body!==body)publishReceipt.current={body,id:crypto.randomUUID()};await publishDraft(draft,publishReceipt.current.id);setNotice('publishedSuccess');onPublished()}}catch(e){setError(errorKey(e));setNotice('')}finally{setBusy(false)}
 }
 const copy=()=>{const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(value.slug||'cnm-draft')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const update=(field:'title_i18n'|'excerpt_i18n'|'body_i18n',text:string)=>{setNotice('');setValue(v=>({...v,[field]:{...v[field],[editLocale]:text},...(field==='title_i18n'&&!slugEdited?{slug:makeSlug(text)}:{})}))}
 return <section className="editor-shell"><header className="editor-toolbar"><div><button type="button" className="back-link" disabled={locked} onClick={close}><Icon name="back" size={18}/>{t('close')}</button><span className="save-state" role="status">{t(busy?'saving':notice|| (dirty?'notSaved':'privateDraft'))}</span></div><div className="editor-toolbar-actions"><button type="button" className="button quiet" onClick={()=>setPreview(true)} disabled={locked}>{t('preview')}</button><button type="button" className="button secondary" disabled={locked||!validVideo} onClick={()=>persist(false)}>{t('saveDraft')}</button><button type="button" className="button" disabled={locked||!validVideo} onClick={()=>persist(true)}>{t(article?.status==='published'||record?.published?'updatePublished':'publish')}</button></div></header>
 {error&&<div className="editor-note"><p className="field-error" role="alert">{t(error)}</p><button type="button" className="text-link" onClick={copy}>{t('copyLocalDraft')}</button></div>}
 <div className="editor-grid"><aside className="editor-aside"><h2>{t('privateDraft')}</h2><Field label={t('urlSlug')} value={value.slug} maxLength={120} disabled={locked} onChange={e=>{setSlugEdited(true);setValue({...value,slug:makeSlug(e.target.value)})}}/><Field label={t('authorCredit')} value={value.author_credit} maxLength={160} disabled={locked} onChange={e=>setValue({...value,author_credit:e.target.value})}/><div className="field"><label htmlFor="article-category">{t('category')}</label><select id="article-category" disabled={locked} value={value.category_id||''} onChange={e=>setValue({...value,category_id:e.target.value||null})}><option value="">CNM</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name_i18n[locale]||c.name_i18n.en||c.slug}</option>)}</select></div><label className="check-field"><input type="checkbox" disabled={locked} checked={value.is_sponsored} onChange={e=>setValue({...value,is_sponsored:e.target.checked})}/>{t('advertising')}</label>{value.is_sponsored&&<Field label={t('sponsorCredit')} value={value.sponsor_credit} maxLength={160} disabled={locked} onChange={e=>setValue({...value,sponsor_credit:e.target.value})}/>}</aside><div className="editor-main"><div className="editor-locales" role="group" aria-label={t('editingLanguage')}>{localeOrder.map(code=><button type="button" key={code} disabled={locked} aria-pressed={editLocale===code} onClick={()=>setEditLocale(code)}>{code.toUpperCase()}</button>)}</div><div className="editor-body"><Field label={t('title')} className="editor-headline" value={value.title_i18n[editLocale]||''} maxLength={250} disabled={locked} onChange={e=>update('title_i18n',e.target.value)}/><TextArea label={t('excerpt')} value={value.excerpt_i18n[editLocale]||''} maxLength={1500} rows={3} disabled={locked} onChange={e=>update('excerpt_i18n',e.target.value)}/><TextArea label={t('body')} value={value.body_i18n[editLocale]||''} maxLength={50000} rows={18} disabled={locked} onChange={e=>update('body_i18n',e.target.value)}/></div><MediaPanel value={value} onChange={setValue} scopeId={id.current} purpose="draft" editLocale={editLocale} disabled={locked} onBusy={setUploading} onValidity={setValidVideo}/></div></div>
 <Dialog open={preview} title={t('preview')+' - '+t('privateDraft')} onClose={()=>setPreview(false)} className="editor-preview"><div className="article-heading"><div className="eyebrow">{value.is_sponsored?t('advertising'):'CNM'}</div><h1>{value.title_i18n[editLocale]||t('untitled')}</h1><p className="article-summary">{value.excerpt_i18n[editLocale]}</p><p>{value.author_credit}</p></div><div className="reading-column">{(value.body_i18n[editLocale]||'').split(/\n{2,}/).map((p,i)=><p key={i}>{p}</p>)}</div><p className="field-help">{t('uploadPrivate')}</p></Dialog></section>
}
