import type {PublicArticle} from '../articles/article.model'
import {validateDraftSnapshot,type DraftSnapshot} from '../../shared/contracts/forms'
export type DraftRecord={id:string;articleId:string|null;intendedArticleId:string;revision:number;baseUpdatedAt:string|null;updatedAt:string;snapshot:DraftSnapshot;published:boolean}
export function emptySnapshot():DraftSnapshot{return {slug:'',category_id:null,author_credit:'',title_i18n:{},excerpt_i18n:{},body_i18n:{},photos:[],video:null,is_sponsored:false,sponsor_credit:''}}
export function articleToSnapshot(article:PublicArticle):DraftSnapshot{return validateDraftSnapshot({slug:article.slug,category_id:article.category_id,author_credit:article.author_credit||'',title_i18n:{...article.title_i18n},excerpt_i18n:{...article.excerpt_i18n},body_i18n:{...article.body_i18n},photos:[...(article.hero?[article.hero]:[]),...(article.gallery||[])].map(photo=>({mediaId:photo.id,alt:photo.alt_i18n||{},caption:photo.caption_i18n||{},credit:photo.credit||''})),video:article.video||null,is_sponsored:article.is_sponsored===true,sponsor_credit:article.sponsor_credit||''})}
export function buildSaveInput(id:string,expectedRevision:number,article:Pick<PublicArticle,'id'|'updated_at'>|null,snapshot:DraftSnapshot){return {id,expectedRevision,articleId:article?.id||null,baseUpdatedAt:article?.updated_at||null,snapshot:validateDraftSnapshot(snapshot)}}
function stable(value:unknown):string{if(Array.isArray(value))return '['+value.map(stable).join(',')+']';if(value&&typeof value==='object')return '{'+Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>JSON.stringify(k)+':'+stable(v)).join(',')+'}';return JSON.stringify(value)}
export function isDraftDirty(a:DraftSnapshot,b:DraftSnapshot){return stable(a)!==stable(b)}
export function photoInputError(file:{size:number;type:string},count:number):string|null{if(count>=11)return 'photoLimit';if(file.size>10485760)return 'imageTooLarge';if(!['image/jpeg','image/png','image/webp','image/avif'].includes(file.type))return 'imageUnsupported';return null}
export function makeSlug(title:string):string{return title.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,120)}
