import {useEffect,useState} from 'react'
import {useLocale} from '../../shared/i18n'
import {api,errorKey} from '../../shared/api'
import {Field,TextArea} from '../../design/Field'
import {Dialog} from '../../design/Dialog'
import {VideoEmbed} from '../media/VideoEmbed'
import type {VideoRef} from '../../shared/media/video'
export type InboxItem={id:string;reference:string;created_at:string;updated_at:string;kind?:string;name:string;email:string;locale:string;category?:string;organization?:string;interest?:string;budget_range?:string;message?:string;title?:string;body?:string;status:string;note?:string;photos?:{uploadId:string}[];video?:VideoRef|null}
export function Inbox({kind}:{kind:'inquiry'|'submission'}){
 const {t}=useLocale(),[items,setItems]=useState<InboxItem[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState<InboxItem|null>(null),[status,setStatus]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[urls,setUrls]=useState<Record<string,string>>({}),[attempt,setAttempt]=useState(0)
 const reload=()=>setAttempt(n=>n+1)
 useEffect(()=>{let active=true;setLoading(true);setError('');api<{items:InboxItem[]}>(kind+'.list').then(result=>{if(active)setItems(result.items)}).catch(e=>{if(active)setError(errorKey(e))}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[kind,attempt])
 const select=(item:InboxItem)=>{setSelected(item);setStatus(item.status);setNote(item.note||'');setUrls({});if(kind==='submission'&&item.photos?.length)api<{urls:Record<string,string>}>('submission.media',{id:item.id}).then(r=>setUrls(r.urls)).catch(()=>{})}
 const save=async()=>{if(!selected||busy)return;setBusy(true);setError('');try{await api(kind+'.update',{id:selected.id,status,note,expectedUpdatedAt:selected.updated_at});setSelected(null);reload()}catch(e){setError(errorKey(e))}finally{setBusy(false)}}
 const options=kind==='inquiry'?['new','discussing','agreed','closed']:['pending','reviewing','accepted','rejected']
 return <div>{loading&&<p role="status">{t('loading')}{'\u2026'}</p>}{error&&<p role="alert" className="field-error">{t(error)}</p>}{!loading&&!items.length&&<p>{t(kind==='inquiry'?'noInquiries':'noSubmissions')}</p>}<div className="editorial-list">{items.map(item=><button type="button" key={item.id} onClick={()=>select(item)}><span><strong>{item.title||item.organization||item.name}</strong><small>{item.reference} {'\u00b7'} {item.email}</small></span><span className="editorial-status">{t(item.status==='new'?'newStatus':item.status)}</span></button>)}</div><Dialog open={Boolean(selected)} title={selected?.title||selected?.organization||t(kind==='inquiry'?'inquiries':'queue')} onClose={()=>{if(!busy)setSelected(null)}}>{selected&&<div className="inbox-detail"><dl><dt>{t('name')}</dt><dd>{selected.name}</dd><dt>{t('email')}</dt><dd><a href={'mailto:'+selected.email}>{selected.email}</a></dd><dt>{t('language')}</dt><dd>{selected.locale.toUpperCase()}</dd>{selected.budget_range&&<><dt>{t('budget')}</dt><dd>{selected.budget_range}</dd></>}</dl><div className="inbox-message">{selected.message||selected.body}</div>{Object.entries(urls).map(([key,url])=><img key={key} src={url} alt={t('approvedMedia')} loading="lazy"/>)}{selected.video&&<VideoEmbed video={selected.video}/>}<div className="field"><label htmlFor="inbox-status">{t('status')}</label><select id="inbox-status" value={status} disabled={busy} onChange={e=>setStatus(e.target.value)}>{options.map(s=><option key={s} value={s}>{t(s==='new'?'newStatus':s)}</option>)}</select></div><TextArea label={t('internalNote')} value={note} maxLength={5000} rows={4} disabled={busy} onChange={e=>setNote(e.target.value)}/><button type="button" className="button" disabled={busy} onClick={save}>{t(busy?'saving':'save')}</button>{error&&<p role="alert" className="field-error">{t(error)}</p>}</div>}</Dialog></div>
}
