import {useRef,useState,useEffect} from 'react'
import {useLocale,type Locale} from '../../shared/i18n'
import {Field} from '../../design/Field'
import {Icon} from '../../design/Icon'
import {api,errorKey,ApiError} from '../../shared/api'
import type {DraftSnapshot,DraftPhoto} from '../../shared/contracts/forms'
import {normalizeVideoUrl,videoSourceUrl} from '../../shared/media/video'
import {uploadPrivateImage} from '../media/uploadClient'
import {photoInputError} from './editorial.model'
export function MediaPanel({value,onChange,scopeId,purpose,editLocale,disabled,onBusy,onValidity,initialPreviews={}}:{value:DraftSnapshot;onChange:(value:DraftSnapshot)=>void;scopeId:string;purpose:'draft'|'submission';editLocale:Locale;disabled:boolean;onBusy:(busy:boolean)=>void;onValidity:(valid:boolean)=>void;initialPreviews?:Record<string,string>}){
 const {t}=useLocale(),input=useRef<HTMLInputElement>(null),latest=useRef(value),[previews,setPreviews]=useState<Record<string,string>>(initialPreviews),[progress,setProgress]=useState<number|null>(null),[error,setError]=useState(''),[videoUrl,setVideoUrl]=useState(value.video?videoSourceUrl(value.video):'');latest.current=value
 const ids=value.photos.filter(p=>p.uploadId).map(p=>p.uploadId!).join(',')
 useEffect(()=>{let active=true;if(ids)api<{urls:Record<string,string>}>('media.preview',{ids:ids.split(',')}).then(result=>{if(active)setPreviews(p=>({...p,...result.urls}))}).catch(()=>{});return()=>{active=false}},[ids])
 useEffect(()=>()=>{Object.values(previews).filter(url=>url.startsWith('blob:')).forEach(URL.revokeObjectURL)},[])
 const upload=async(file?:File)=>{if(!file||disabled)return;const issue=photoInputError(file,latest.current.photos.length);if(issue){setError(t(issue));return}setError('');onBusy(true);setProgress(0);try{const asset=await uploadPrivateImage(file,purpose,scopeId,setProgress);setPreviews(p=>({...p,[asset.id]:asset.preview}));onChange({...latest.current,photos:[...latest.current.photos,{uploadId:asset.id,caption:{},alt:{},credit:''}]})}catch(e){setError(t(e instanceof ApiError&&['imageTooLarge','imageUnsupported','imageDimensions'].includes(e.code)?e.code:errorKey(e)))}finally{onBusy(false);setProgress(null);if(input.current)input.current.value=''}}
 const changePhoto=(index:number,patch:Partial<DraftPhoto>)=>onChange({...value,photos:value.photos.map((p,i)=>i===index?{...p,...patch}:p)})
 const move=(index:number,direction:number)=>{const photos=[...value.photos];[photos[index],photos[index+direction]]=[photos[index+direction],photos[index]];onChange({...value,photos})}
 return <section className="media-panel"><h2>{t('heroImage')}</h2><p className="field-help">{t('photoHelp')}</p><p className="field-help">{t(purpose==='draft'?'uploadPrivate':'submissionPrivate')}</p><div className="media-preview-grid">{value.photos.map((photo,index)=>{const key=photo.uploadId||photo.mediaId!;return <div className="media-preview-item" key={key}>{previews[key]?<img src={previews[key]} alt={photo.alt[editLocale]||t('heroImage')}/>:<div className="photo-unavailable">{t('approvedMedia')}</div>}<div className="media-order"><strong>{index===0?t('heroImage'):String(index+1)}</strong><button type="button" disabled={disabled||index===0} aria-label={t('movePhotoUp')} onClick={()=>move(index,-1)}>{'\u2191'}</button><button type="button" disabled={disabled||index===value.photos.length-1} aria-label={t('movePhotoDown')} onClick={()=>move(index,1)}>{'\u2193'}</button><button type="button" disabled={disabled} aria-label={t('removePhoto')} onClick={()=>onChange({...value,photos:value.photos.filter((_,i)=>i!==index)})}><Icon name="close" size={17}/></button></div><Field label={t('caption')} value={photo.caption[editLocale]||''} maxLength={1000} disabled={disabled} onChange={e=>changePhoto(index,{caption:{...photo.caption,[editLocale]:e.target.value}})}/><Field label={t('photoAlt')} value={photo.alt[editLocale]||''} maxLength={500} disabled={disabled} onChange={e=>changePhoto(index,{alt:{...photo.alt,[editLocale]:e.target.value}})}/><Field label={t('photoCredit')} value={photo.credit} maxLength={160} disabled={disabled} onChange={e=>changePhoto(index,{credit:e.target.value})}/></div>})}</div><input ref={input} type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={e=>upload(e.target.files?.[0])} hidden/><button type="button" className="button secondary" disabled={disabled||value.photos.length>=11} onClick={()=>input.current?.click()}><Icon name="image"/>{t('uploadImage')}</button>{progress!==null&&<div role="status"><p>{t('processingImage')} {Math.round(progress)}%</p><progress value={progress} max={100}/></div>}{error&&<p role="alert" className="field-error">{error}</p>}<Field label={t('videoUrl')} type="url" value={videoUrl} maxLength={2048} disabled={disabled} error={videoUrl.trim()&&!normalizeVideoUrl(videoUrl)?t('videoInvalid'):undefined} onChange={e=>{const url=e.target.value;setVideoUrl(url);const parsed=normalizeVideoUrl(url);onValidity(!url.trim()||Boolean(parsed));if(!url.trim()||parsed)onChange({...value,video:parsed})}}/><p className="field-help">{t('videoPrivacy')}</p></section>
}
