import {useEffect,useRef,useState,type FormEvent} from 'react'
import {useLocale} from '../../shared/i18n'
import {useAuth} from '../account/AuthProvider'
import {SiteLink} from '../../app/router'
import {Dialog} from '../../design/Dialog'
import {Icon} from '../../design/Icon'
import {Field,TextArea} from '../../design/Field'
import {api,errorKey} from '../../shared/api'
export function CommunityPage(){
 const {t,locale}=useLocale(),{session}=useAuth(),[open,setOpen]=useState<'song'|'dedication'|null>(null),[form,setForm]=useState({name:'',title:'',artist:'',recipient:'',message:''}),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[error,setError]=useState(''),request=useRef({body:'',id:''})
 const query=window.location.search
 useEffect(()=>{const value=new URLSearchParams(query).get('form');if(value==='song'||value==='dedication'){setOpen(value);setDone(false);setError('')}},[query])
 const start=(value:'song'|'dedication')=>{setOpen(value);setDone(false);setError('')}
 const update=(field:keyof typeof form)=>(e:{target:{value:string}})=>setForm(v=>({...v,[field]:e.target.value}))
 const submit=async(e:FormEvent)=>{e.preventDefault();if(busy||!session)return;setBusy(true);setError('');try{const body=JSON.stringify({...form,locale,kind:open});if(body!==request.current.body)request.current={body,id:crypto.randomUUID()};await api('radio.'+open,{...form,locale},request.current.id);setDone(true)}catch(e){setError(errorKey(e))}finally{setBusy(false)}}
 return <div className="container standard-page"><header className="page-heading"><span className="eyebrow">CNM</span><h1>{t('community')}</h1><p>{t('communityBody')}</p></header><div className="community-actions">{[['music','requestSong','requestSongBody','song'],['heart','dedication','dedicationBody','dedication']].map(([icon,head,body,kind])=><button type="button" key={head} className="community-action" onClick={()=>start(kind as 'song'|'dedication')}><Icon name={icon as 'music'|'heart'}/><span><strong>{t(head)}</strong><small>{t(body)}</small></span><Icon name="arrow"/></button>)}<SiteLink className="community-action" to="/submit-story"><Icon name="file"/><span><strong>{t('submitArticle')}</strong><small>{t('submitArticleBody')}</small></span><Icon name="arrow"/></SiteLink><SiteLink className="community-action" to="/support"><Icon name="heart"/><span><strong>{t('supportCnm')}</strong><small>{t('supportBody')}</small></span><Icon name="arrow"/></SiteLink></div>
 <Dialog open={Boolean(open)} title={t(open==='song'?'requestSong':'dedication')} onClose={()=>setOpen(null)}>{!session?<div className="dialog-body"><h3>{t('signInRequired')}</h3><p>{t('signInBody')}</p><SiteLink to="/account" className="button" onClick={()=>setOpen(null)}>{t('signIn')}</SiteLink></div>:done?<div className="dialog-body confirmation" role="status"><span className="confirmation-tick">{'\u2713'}</span><h3>{t('submitted')}</h3><button type="button" className="button" onClick={()=>setOpen(null)}>{t('close')}</button></div>:<form className="native-form dialog-body" onSubmit={submit}><Field label={t('name')} value={form.name} onChange={update('name')} autoComplete="name" maxLength={80} required/>{open==='dedication'&&<Field label={t('recipient')} value={form.recipient} onChange={update('recipient')} maxLength={80} required/>}<Field label={t('songTitle')} value={form.title} onChange={update('title')} maxLength={160} required={open==='song'}/><Field label={t('artist')} value={form.artist} onChange={update('artist')} maxLength={160}/><TextArea label={t('message')} value={form.message} onChange={update('message')} maxLength={open==='song'?500:700} required={open==='dedication'} rows={4}/>{error&&<p className="field-error" role="alert">{t(error)}</p>}<p className="field-help">{t('reviewNote')}</p><button disabled={busy} className="button">{t(busy?'sending':'send')}</button></form>}</Dialog></div>
}
