import {useRef,useState,type FormEvent} from 'react'
import {Field,TextArea} from '../../design/Field'
import {useLocale} from '../../shared/i18n'
import {SiteLink} from '../../app/router'
import {api,errorKey} from '../../shared/api'
import {categories,CONTACT_NOTICE_VERSION,validateInquiry,type InquiryCategory} from '../../shared/contracts/forms'
const labels:Record<InquiryCategory,string>={general:'general',technical:'technical',sponsorship:'sponsor',editorial:'editorialIdea',correction:'correction',copyright:'copyrightConcern'}
export function InquiryForm({sponsorship=false}:{sponsorship?:boolean}){
 const {locale,t}=useLocale(),query=new URLSearchParams(window.location.search),initial=query.get('category')
 const [form,setForm]=useState({name:'',email:'',category:sponsorship?'sponsorship':categories.includes(initial as InquiryCategory)?initial!:'general',message:'',relevantUrl:'',organization:'',interest:'radio',budgetRange:''}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reference,setReference]=useState(''),lastRequest=useRef({body:'',id:''})
 const isSponsor=sponsorship||form.category==='sponsorship'
 const field=(key:keyof typeof form)=>(event:{target:{value:string}})=>setForm(v=>({...v,[key]:event.target.value}))
 const submit=async(event:FormEvent)=>{event.preventDefault();if(busy)return;setError('');setBusy(true);try{
  const payload=validateInquiry({...form,category:sponsorship?'sponsorship':form.category,locale,policyVersion:CONTACT_NOTICE_VERSION}),body=JSON.stringify(payload)
  if(body!==lastRequest.current.body)lastRequest.current={body,id:crypto.randomUUID()}
  const result=await api<{reference:string;stored:boolean}>('inquiry.submit',payload,lastRequest.current.id)
  if(!result.stored||!result.reference)throw new Error('not_stored');setReference(result.reference)
 }catch(e){setError(errorKey(e))}finally{setBusy(false)}}
 if(reference)return <section className="confirmation" role="status"><span className="confirmation-tick">{'\u2713'}</span><h2>{t('submitted')}</h2><p>{t('inboxSuccess')}</p><span className="receipt-label">{t('reference')}</span><code>{reference}</code><SiteLink to="/" className="text-link">{t('backHome')} {'\u2192'}</SiteLink></section>
 return <form className="native-form inquiry-form" onSubmit={submit}><div className="form-title"><h2>{t(sponsorship?'partner':'contact')}</h2></div>{isSponsor&&<Field label={t('business')} value={form.organization} onChange={field('organization')} maxLength={160} autoComplete="organization" required/>}<div className="form-columns"><Field label={t('name')} value={form.name} onChange={field('name')} maxLength={80} autoComplete="name" required/><Field label={t('email')} type="email" value={form.email} onChange={field('email')} maxLength={254} autoComplete="email" required/></div><div className="field"><label htmlFor={sponsorship?'sponsor-interest':'contact-category'}>{t('subject')} *</label>{sponsorship?<select id="sponsor-interest" value={form.interest} onChange={field('interest')}><option value="radio">{t('sponsorRadio')}</option><option value="website">{t('sponsorDigital')}</option><option value="community">{t('sponsorCommunity')}</option></select>:<select id="contact-category" value={form.category} onChange={field('category')}>{categories.map(c=><option key={c} value={c}>{t(labels[c])}</option>)}</select>}</div>{isSponsor&&!sponsorship&&<div className="field"><label htmlFor="contact-sponsor-interest">{t('subject')}</label><select id="contact-sponsor-interest" value={form.interest} onChange={field('interest')}><option value="radio">{t('sponsorRadio')}</option><option value="website">{t('sponsorDigital')}</option><option value="community">{t('sponsorCommunity')}</option></select></div>}<TextArea label={t('message')} value={form.message} onChange={field('message')} maxLength={5000} rows={6} required/>{isSponsor?<Field label={t('budget')} value={form.budgetRange} onChange={field('budgetRange')} maxLength={80}/>:<Field label={t('relevantUrl')} type="url" value={form.relevantUrl} onChange={field('relevantUrl')} maxLength={2048}/>}<p className="form-privacy">{t('privacyNotice')} <SiteLink to="/privacy">{t('privacy')}</SiteLink></p>{error&&<p className="field-error" role="alert">{t(error)}</p>}<button className="button" disabled={busy}>{t(busy?'sending':'sendInquiry')} <span aria-hidden="true">{'\u2192'}</span></button></form>
}
