import {useRef,useState,type FormEvent} from 'react'
import {useLocale,localeOrder,localeNames,type Locale} from '../../shared/i18n'
import {useAuth} from '../account/AuthProvider'
import {SiteLink,useNavigationGuard} from '../../app/router'
import {Field,TextArea} from '../../design/Field'
import {MediaPanel} from '../editorial/MediaPanel'
import {emptySnapshot} from '../editorial/editorial.model'
import {api,errorKey} from '../../shared/api'
import {validateSubmission,SUBMISSION_NOTICE_VERSION} from '../../shared/contracts/submission'
export function SubmitStoryPage(){
 const {session}=useAuth(),{t,locale}=useLocale(),[language,setLanguage]=useState<Locale>(locale),[name,setName]=useState(''),[snapshot,setSnapshot]=useState(emptySnapshot),[rights,setRights]=useState(false),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[validVideo,setValidVideo]=useState(true),[error,setError]=useState(''),[reference,setReference]=useState(''),scopeId=useRef(crypto.randomUUID()),receipt=useRef<{body:string;id:string}|null>(null)
 const locked=busy||uploading
 useNavigationGuard(!reference&&Boolean(name||Object.values(snapshot.body_i18n).some(Boolean)),t('unsaved'))
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!session||locked||!validVideo)return;setError('');if(!rights){setError('permissionRequired');return}setBusy(true);try{const payload=validateSubmission({name,title:snapshot.title_i18n[language]||'',body:snapshot.body_i18n[language]||'',locale:language,scopeId:scopeId.current,photos:snapshot.photos,video:snapshot.video,rightsConfirmed:true,policyVersion:SUBMISSION_NOTICE_VERSION}),body=JSON.stringify(payload);if(receipt.current?.body!==body)receipt.current={body,id:crypto.randomUUID()};const result=await api<{stored:true;reference:string}>('submission.submit',payload,receipt.current.id);setReference(result.reference)}catch(e){setError(errorKey(e))}finally{setBusy(false)}}
 if(!session)return <div className="container standard-page"><header className="page-heading"><span className="eyebrow">CNM</span><h1>{t('submitArticle')}</h1><p>{t('submissionPrivate')}</p></header><div className="editorial-guard"><h2>{t('signInRequired')}</h2><p>{t('noAccountListen')}</p><SiteLink to="/account" className="button">{t('signIn')}</SiteLink></div></div>
 return <div className="container standard-page"><header className="page-heading"><span className="eyebrow">CNM</span><h1>{t('submitArticle')}</h1><p>{t('submissionPrivate')}</p></header>{reference?<div className="form-confirmation" role="status"><h2>{t('submitted')}</h2><p>{t('reference')}: {reference}</p><SiteLink to="/community">{t('community')}</SiteLink></div>:<form className="native-form submission-form" onSubmit={submit}><Field label={t('name')} required value={name} maxLength={80} disabled={locked} onChange={e=>setName(e.target.value)}/><div className="field"><label htmlFor="story-language">{t('editingLanguage')}</label><select id="story-language" value={language} disabled={locked} onChange={e=>setLanguage(e.target.value as Locale)}>{localeOrder.map(code=><option key={code} value={code}>{localeNames[code]}</option>)}</select></div><Field label={t('title')} required value={snapshot.title_i18n[language]||''} maxLength={250} disabled={locked} onChange={e=>setSnapshot({...snapshot,title_i18n:{...snapshot.title_i18n,[language]:e.target.value}})}/><TextArea label={t('story')} required value={snapshot.body_i18n[language]||''} rows={12} maxLength={50000} disabled={locked} onChange={e=>setSnapshot({...snapshot,body_i18n:{...snapshot.body_i18n,[language]:e.target.value}})}/><MediaPanel value={snapshot} onChange={setSnapshot} scopeId={scopeId.current} purpose="submission" editLocale={language} disabled={locked} onBusy={setUploading} onValidity={setValidVideo}/><label className="check-field"><input type="checkbox" required checked={rights} disabled={locked} onChange={e=>setRights(e.target.checked)}/><span>{t('rightsConfirm')}</span></label><p className="field-help">{t('reviewNote')} <SiteLink to="/editorial-policy">{t('standardsHeading')}</SiteLink></p>{error&&<p role="alert" className="field-error">{t(error)}</p>}<button className="button" disabled={locked||!validVideo}>{t(busy?'sending':'send')}</button></form>}</div>
}
