// Original review drafts. These are not operator-approved contracts or licensing claims.
type Row = {id:string;heading:[string,string,string,string];body:[string,string,string,string]}
export const policyRows:Record<'terms'|'privacy'|'editorial',Row[]>={
terms:[
{id:'service',heading:['The service','Le service','S\u00e8vis la','El servicio'],body:[
'Creole Network Media (CNM) brings together radio listening, articles, programs and community participation. These proposed terms cover this website and its radio player. Reading and listening do not require an account. Station operator details and the effective date must be confirmed before this draft becomes final.',
'Creole Network Media (CNM) r\u00e9unit \u00e9coute radio, articles, programmes et participation communautaire. Ces conditions propos\u00e9es concernent ce site et son lecteur radio. La lecture et l\u2019\u00e9coute ne n\u00e9cessitent pas de compte. Les informations sur l\u2019exploitant et la date d\u2019entr\u00e9e en vigueur doivent \u00eatre confirm\u00e9es avant finalisation.',
'Creole Network Media (CNM) mete radyo, atik, pwogram ak patisipasyon kominot\u00e8 ansanm. Kondisyon sa yo se pwopozisyon pou sit sa a ak lekt\u00e8 radyo li. Ou pa bezwen kont pou li oswa koute. Enf\u00f2masyon sou operat\u00e8 estasyon an ak dat aplikasyon an dwe konfime anvan bouyon sa a vin final.',
'Creole Network Media (CNM) re\u00fane radio, art\u00edculos, programas y participaci\u00f3n comunitaria. Estos t\u00e9rminos propuestos cubren este sitio y su reproductor de radio. No necesitas una cuenta para leer o escuchar. Los datos del operador y la fecha de entrada en vigor deben confirmarse antes de finalizar el borrador.']},
{id:'availability',heading:['Listening and availability','\u00c9coute et disponibilit\u00e9','Koute ak disponiblite','Escucha y disponibilidad'],body:[
'Broadcasts, program schedules and individual items may change or become unavailable. Playback depends on the station stream, your device and your connection. Your internet or mobile provider determines data charges. A play control or a published schedule is not a guarantee of uninterrupted broadcasting.',
'Les diffusions, grilles de programmes et contenus peuvent changer ou devenir indisponibles. La lecture d\u00e9pend du flux de la station, de votre appareil et de votre connexion. Votre fournisseur fixe les frais de donn\u00e9es. Un bouton de lecture ou un programme publi\u00e9 ne garantit pas une diffusion ininterrompue.',
'Difizyon, or\u00e8 pwogram ak kontni yo ka chanje oswa pa disponib. Lekt\u00e8 a depann de stream estasyon an, apar\u00e8y ou ak koneksyon ou. Founis\u00e8 ent\u00e8n\u00e8t oswa mobil ou fikse pri done yo. Yon bouton pou jwe oswa yon or\u00e8 pibliye pa garanti difizyon san ent\u00e8ipsyon.',
'Las transmisiones, los horarios y el contenido pueden cambiar o dejar de estar disponibles. La reproducci\u00f3n depende de la emisora, tu dispositivo y tu conexi\u00f3n. Tu proveedor determina los cargos de datos. Un bot\u00f3n de reproducci\u00f3n o un horario publicado no garantiza una emisi\u00f3n ininterrumpida.']},
{id:'accounts',heading:['Accounts and responsible use','Comptes et utilisation responsable','Kont ak itilizasyon responsab','Cuentas y uso responsable'],body:[
'Keep your account information accurate and your sign-in details private. Do not impersonate another person, bypass access controls, submit malware or spam, or interfere with the station services. Contact CNM if you suspect unauthorized account use. Administrator status is assigned by the station, not obtained by creating an ordinary account.',
'Veillez \u00e0 l\u2019exactitude des informations de votre compte et prot\u00e9gez vos identifiants. N\u2019usurpez pas d\u2019identit\u00e9, ne contournez pas les acc\u00e8s et n\u2019envoyez ni logiciels malveillants ni spam. Contactez CNM en cas d\u2019utilisation non autoris\u00e9e. Le statut administrateur est attribu\u00e9 par la station, pas par la simple cr\u00e9ation d\u2019un compte.',
'Kenbe enf\u00f2masyon kont ou k\u00f2r\u00e8k epi pwoteje idantifyan ou yo. Pa pran idantite yon l\u00f2t moun, pa kontoune aks\u00e8, pa voye viris oswa spam, epi pa deranje s\u00e8vis estasyon an. Kontakte CNM si ou sisp\u00e8k yon itilizasyon san p\u00e8misyon. Estasyon an bay w\u00f2l admin; kreye yon kont n\u00f2mal pa bay w\u00f2l sa a.',
'Mant\u00e9n tus datos de cuenta correctos y tus credenciales privadas. No suplantes a otra persona, eludas los controles de acceso, env\u00edes malware o spam ni interfieras con los servicios. Contacta con CNM si sospechas un uso no autorizado. La emisora asigna el rol de administrador; crear una cuenta no lo otorga.']},
{id:'dedications',heading:['Requests and dedications','Demandes musicales et d\u00e9dicaces','Demann mizik ak dedikas','Solicitudes y dedicatorias'],body:[
'A request does not guarantee that a song or message will be broadcast. CNM may decline or edit a dedication for length, clarity, safety or programming. When you submit a dedication for the radio, you ask CNM to read the message and names you include. Do not include confidential information or another person\u2019s private contact details.',
'Une demande ne garantit pas la diffusion d\u2019une chanson ou d\u2019un message. CNM peut refuser ou adapter une d\u00e9dicace pour des raisons de longueur, de clart\u00e9, de s\u00e9curit\u00e9 ou de programmation. En envoyant une d\u00e9dicace radio, vous demandez la lecture du message et des noms inclus. N\u2019incluez pas d\u2019informations confidentielles ni les coordonn\u00e9es priv\u00e9es d\u2019autrui.',
'Yon demann pa garanti yo pral pase yon mizik oswa yon mesaj. CNM ka refize oswa adapte yon dedikas selon long\u00e8, klate, sekirite oswa pwogramasyon. L\u00e8 ou voye yon dedikas pou radyo a, ou mande CNM pou li mesaj la ak non ou mete yo. Pa mete enf\u00f2masyon konfidansy\u00e8l oswa kontak prive yon l\u00f2t moun.',
'Una solicitud no garantiza que se emita una canci\u00f3n o un mensaje. CNM puede rechazar o adaptar una dedicatoria por extensi\u00f3n, claridad, seguridad o programaci\u00f3n. Al enviarla para la radio, pides que CNM lea el mensaje y los nombres incluidos. No a\u00f1adas datos confidenciales ni datos de contacto privados de otra persona.']},
{id:'contributions',heading:['Articles, photographs and linked media','Articles, photographies et m\u00e9dias li\u00e9s','Atik, foto ak medya ki gen lyen','Art\u00edculos, fotos y medios enlazados'],body:[
'You retain ownership of your original work. Submit only material you have the right to share, including any required permissions from photographers or people represented. Submission allows CNM to receive and review the material; it does not guarantee publication. Publication permission and any substantial edits or translations should be agreed with the contributor before publication. A proposed publication license must be limited and non-exclusive, not a transfer of ownership.',
'Vous conservez la propri\u00e9t\u00e9 de vos cr\u00e9ations. Ne soumettez que des contenus que vous avez le droit de partager, avec les autorisations n\u00e9cessaires des photographes ou personnes repr\u00e9sent\u00e9es. L\u2019envoi permet \u00e0 CNM de recevoir et examiner le contenu, sans garantie de publication. L\u2019autorisation de publier, les modifications importantes et les traductions doivent \u00eatre convenues avant publication. La licence propos\u00e9e doit \u00eatre limit\u00e9e et non exclusive, sans transfert de propri\u00e9t\u00e9.',
'Ou rete pwopriyet\u00e8 travay orijinal ou. Voye s\u00e8lman kontni ou gen dwa pataje, ak p\u00e8misyon ki neses\u00e8 nan men fotograf oswa moun ki ladan l. L\u00e8 ou voye kontni an, CNM ka resevwa l epi revize l; sa pa garanti piblikasyon. Otorizasyon pou pibliye, gwo chanjman oswa tradiksyon dwe diskite ak moun ki kontribye a anvan piblikasyon. Lisans yo pwopoze a dwe limite, pa eksklizif, epi li pa dwe transfere pwopriyete a.',
'Conservas la propiedad de tu trabajo original. Env\u00eda solo contenido que tengas derecho a compartir, con los permisos necesarios de fot\u00f3grafos o personas representadas. El env\u00edo permite que CNM lo reciba y revise, pero no garantiza su publicaci\u00f3n. El permiso para publicar y las modificaciones o traducciones importantes deben acordarse previamente. La licencia propuesta debe ser limitada y no exclusiva, sin transferir la propiedad.']},
{id:'partners',heading:['Sponsorship and support','Partenariats et soutien','Patn\u00e8 ak sip\u00f2','Patrocinios y apoyo'],body:[
'A sponsorship inquiry does not book space or form a contract. Prices, dates, placements, disclosures, cancellation and deliverables require a separate written agreement. Online support is available only through a destination configured by the station. This website does not collect card details. No tax treatment is promised for contributions.',
'Une demande de partenariat ne r\u00e9serve aucun espace et ne constitue pas un contrat. Prix, dates, placements, mentions publicitaires, annulation et prestations requi\u00e8rent un accord \u00e9crit distinct. Le soutien en ligne passe uniquement par une destination configur\u00e9e par la station. Ce site ne recueille pas de donn\u00e9es de carte bancaire. Aucun traitement fiscal n\u2019est promis.',
'Yon demann patn\u00e8 pa rez\u00e8ve plas epi li pa yon kontra. Pri, dat, plasman, mansyon piblisite, anilasyon ak sa pou livre yo mande yon ak\u00f2 ekri apa. Sip\u00f2 sou ent\u00e8n\u00e8t disponib s\u00e8lman atrav\u00e8 yon destinasyon estasyon an konfigire. Sit sa a pa kolekte enf\u00f2masyon kat labank. Nou pa pwom\u00e8t avantaj fiskal pou kontribisyon yo.',
'Una consulta de patrocinio no reserva espacio ni constituye un contrato. Los precios, fechas, espacios, identificaci\u00f3n publicitaria, cancelaciones y entregables requieren un acuerdo escrito separado. El apoyo en l\u00ednea solo est\u00e1 disponible mediante un destino configurado por la emisora. Este sitio no recoge datos de tarjetas. No se promete ning\u00fan tratamiento fiscal.']},
{id:'external',heading:['External media and content rights','M\u00e9dias externes et droits','Medya ekst\u00e8n ak dwa','Medios externos y derechos'],body:[
'External videos and websites are provided by their respective services and may have separate terms, privacy practices or geographic restrictions. Do not redistribute CNM content without permission except where the law allows it. These website terms do not grant music broadcasting, recording or other third-party rights to the station or to listeners.',
'Les vid\u00e9os et sites externes rel\u00e8vent de leurs fournisseurs et peuvent avoir leurs propres conditions, pratiques de confidentialit\u00e9 ou restrictions g\u00e9ographiques. Ne redistribuez pas les contenus CNM sans autorisation, sauf si la loi le permet. Ces conditions ne conf\u00e8rent aucun droit musical, de diffusion, d\u2019enregistrement ou autre droit de tiers \u00e0 la station ou aux auditeurs.',
'Videyo ak sit ekst\u00e8n yo soti nan l\u00f2t s\u00e8vis ki ka gen kondisyon, pratik konfidansyalite oswa restriksyon jewografik pa yo. Pa redistribye kontni CNM san p\u00e8misyon, sof l\u00e8 lalwa p\u00e8m\u00e8t sa. Kondisyon sit sa a pa bay estasyon an oswa odit\u00e8 yo dwa sou mizik, difizyon, anrejistreman oswa l\u00f2t dwa twazy\u00e8m pati.',
'Los videos y sitios externos pertenecen a sus proveedores y pueden tener condiciones, pr\u00e1cticas de privacidad o restricciones geogr\u00e1ficas propias. No redistribuyas contenido de CNM sin permiso salvo cuando la ley lo permita. Estos t\u00e9rminos no conceden a la emisora ni a sus oyentes derechos musicales, de emisi\u00f3n, grabaci\u00f3n ni otros derechos de terceros.']},
{id:'complaints',heading:['Questions, corrections and changes','Questions, corrections et changements','Kesyon, koreksyon ak chanjman','Preguntas, correcciones y cambios'],body:[
'Use the Contact page for a correction, copyright concern, account issue or other complaint. Include the relevant URL and enough information to explain the issue without sending unnecessary confidential data. CNM may remove or restrict material while reviewing a concern. Final terms, including any lawful limitations and an effective date, require station and legal review; this draft does not waive your statutory rights.',
'Utilisez la page Contact pour une correction, un probl\u00e8me de droits d\u2019auteur, de compte ou toute autre r\u00e9clamation. Indiquez le lien concern\u00e9 et les informations utiles, sans donn\u00e9es confidentielles superflues. CNM peut retirer ou restreindre un contenu pendant son examen. Les conditions finales, leurs limites licites et leur date d\u2019effet requi\u00e8rent une validation de la station et une revue juridique ; ce projet ne supprime pas vos droits l\u00e9gaux.',
'Itilize paj Kontak la pou yon koreksyon, yon pwobl\u00e8m dwa ot\u00e8, kont oswa l\u00f2t plent. Mete lyen ki kons\u00e8ne a ak ase enf\u00f2masyon pou eksplike pwobl\u00e8m nan, san done konfidansy\u00e8l ki pa neses\u00e8. CNM ka retire oswa limite yon kontni pandan revizyon an. Kondisyon final yo, limit legal yo ak dat aplikasyon yo mande validasyon estasyon an ak revizyon legal; bouyon sa a pa retire dwa lalwa ba ou.',
'Usa la p\u00e1gina Contacto para correcciones, derechos de autor, problemas de cuenta u otras reclamaciones. Incluye el enlace y la informaci\u00f3n necesaria sin enviar datos confidenciales innecesarios. CNM puede retirar o restringir material durante la revisi\u00f3n. Los t\u00e9rminos finales, sus limitaciones legales y su fecha de vigencia requieren revisi\u00f3n de la emisora y asesor\u00eda jur\u00eddica; este borrador no elimina tus derechos legales.']}
],
privacy:[
{id:'scope',heading:['Scope of this notice','Port\u00e9e de cette notice','Sa politik sa a kouvri','Alcance de este aviso'],body:[
'This draft describes the CNM website features being delivered. It is not a claim that every station or mobile-app process has been audited. Contact CNM about a specific privacy question before submitting sensitive material. The station must confirm its operator details, retention schedule and final procedures before adopting this notice.',
'Ce projet d\u00e9crit les fonctions du site CNM livr\u00e9es ici. Il ne signifie pas que tous les processus de la station ou de l\u2019application mobile ont \u00e9t\u00e9 audit\u00e9s. Contactez CNM avant d\u2019envoyer des contenus sensibles. La station doit confirmer son exploitant, ses dur\u00e9es de conservation et ses proc\u00e9dures avant d\u2019adopter cette notice.',
'Bouyon sa a dekri fonksyon sit CNM yo ap livre a. Li pa vle di yo verifye tout pwosesis estasyon an oswa aplikasyon mobil la. Kontakte CNM anvan ou voye kontni sansib. Estasyon an dwe konfime enf\u00f2masyon operat\u00e8 li, dire kons\u00e8vasyon done yo ak pwosedi final li anvan li adopte politik sa a.',
'Este borrador describe las funciones del sitio CNM que se entregan. No afirma que se hayan auditado todos los procesos de la emisora o la aplicaci\u00f3n. Contacta con CNM antes de enviar material sensible. La emisora debe confirmar sus datos de operador, los plazos de conservaci\u00f3n y sus procedimientos antes de adoptar el aviso.']},
{id:'data',heading:['Information you provide','Informations fournies','Enf\u00f2masyon ou bay','Informaci\u00f3n que proporcionas'],body:[
'An account uses your email, authentication credentials, display name and preferences. Forms can collect your name, email, message, selected category, optional business and budget details, story text, photos and video links. You choose what to include. Do not send payment-card details, identity documents or other information that is unnecessary for the request.',
'Un compte utilise votre e-mail, vos identifiants, votre nom affich\u00e9 et vos pr\u00e9f\u00e9rences. Les formulaires peuvent recueillir nom, e-mail, message, cat\u00e9gorie, entreprise et budget facultatifs, texte, photos et liens vid\u00e9o. Vous choisissez les informations envoy\u00e9es. N\u2019envoyez ni carte bancaire, ni pi\u00e8ce d\u2019identit\u00e9, ni donn\u00e9es inutiles \u00e0 votre demande.',
'Yon kont itilize im\u00e8l ou, idantifyan ou, non ki par\u00e8t ak preferans ou. F\u00f2mil\u00e8 yo ka kolekte non, im\u00e8l, mesaj, kategori, enf\u00f2masyon biznis ak bidj\u00e8 opsyon\u00e8l, t\u00e8ks atik, foto ak lyen videyo. Ou chwazi sa ou mete. Pa voye enf\u00f2masyon kat labank, py\u00e8s idantite oswa l\u00f2t enf\u00f2masyon ki pa neses\u00e8 pou demann lan.',
'Una cuenta utiliza tu correo, credenciales, nombre visible y preferencias. Los formularios pueden recoger nombre, correo, mensaje, categor\u00eda, empresa y presupuesto opcionales, texto, fotos y enlaces de video. T\u00fa eliges qu\u00e9 incluir. No env\u00edes datos de tarjetas, documentos de identidad ni informaci\u00f3n innecesaria para la consulta.']},
{id:'purpose',heading:['Why this information is used','Utilisation des informations','Poukisa nou itilize enf\u00f2masyon sa yo','Para qu\u00e9 se usa'],body:[
'Information supports sign-in, your preferences, editorial review, responding to inquiries and protecting the service from abuse. An inquiry does not subscribe you to marketing. A stored-message confirmation means the message reached the CNM inbox; it does not mean an email was delivered or a sponsorship was booked.',
'Les informations servent \u00e0 la connexion, aux pr\u00e9f\u00e9rences, \u00e0 l\u2019examen \u00e9ditorial, aux r\u00e9ponses et \u00e0 la protection du service. Une demande ne vous inscrit pas \u00e0 des communications commerciales. Une confirmation d\u2019enregistrement signifie que le message est dans la bo\u00eete CNM, pas qu\u2019un e-mail a \u00e9t\u00e9 livr\u00e9 ou un partenariat r\u00e9serv\u00e9.',
'Enf\u00f2masyon yo s\u00e8vi pou koneksyon, preferans, revizyon redaksyon, repons pou demann ak pwoteksyon kont abi. Yon demann pa enskri ou nan piblisite. Konfimasyon anrejistreman vle di mesaj la rive nan bwat CNM, pa ke yon im\u00e8l livre oswa yon patenarya rez\u00e8ve.',
'Los datos permiten iniciar sesi\u00f3n, guardar preferencias, revisar contribuciones, responder consultas y proteger el servicio. Una consulta no te suscribe a publicidad. La confirmaci\u00f3n de almacenamiento significa que el mensaje lleg\u00f3 a la bandeja de CNM, no que se envi\u00f3 un correo ni se reserv\u00f3 un patrocinio.']},
{id:'providers',heading:['Hosting and external services','H\u00e9bergement et services externes','Eb\u00e8jman ak s\u00e8vis ekst\u00e8n','Alojamiento y servicios externos'],body:[
'The website uses Supabase for authentication, database records and media storage, and GitHub Pages for website hosting. Infrastructure providers may process network and security logs. A YouTube or Vimeo player loads only when you choose to load that video; the provider then receives a request and applies its own practices. External support links have their own payment and privacy terms.',
'Le site utilise Supabase pour l\u2019authentification, les donn\u00e9es et les m\u00e9dias, et GitHub Pages pour l\u2019h\u00e9bergement. Les fournisseurs peuvent traiter des journaux r\u00e9seau et de s\u00e9curit\u00e9. Le lecteur YouTube ou Vimeo se charge lorsque vous le choisissez ; le fournisseur re\u00e7oit alors une requ\u00eate et applique ses pratiques. Les liens externes de soutien ont leurs propres conditions de paiement et de confidentialit\u00e9.',
'Sit la itilize Supabase pou otantifikasyon, dosye nan bazdone ak medya, epi GitHub Pages pou eb\u00e8jman. Founis\u00e8 yo ka trete jounal rezo ak sekirite. Lekt\u00e8 YouTube oswa Vimeo chaje l\u00e8 ou chwazi jwe videyo a; founis\u00e8 a resevwa yon demann epi li aplike pratik pa li. Lyen sip\u00f2 ekst\u00e8n yo gen pw\u00f2p kondisyon peman ak konfidansyalite yo.',
'El sitio utiliza Supabase para autenticaci\u00f3n, registros y medios, y GitHub Pages para alojamiento. Los proveedores pueden procesar registros de red y seguridad. YouTube o Vimeo solo se carga cuando eliges cargar ese video; entonces el proveedor recibe una solicitud y aplica sus propias pr\u00e1cticas. Los enlaces externos de apoyo tienen sus propios t\u00e9rminos de pago y privacidad.']},
{id:'visibility',heading:['Private and published material','Contenus priv\u00e9s et publi\u00e9s','Kontni prive ak kontni pibliye','Material privado y publicado'],body:[
'Inquiries and new contribution attachments are for authorized review, not a public feed. Material deliberately published by an authorized publisher is public and may be copied or cached by others. Removing it from CNM cannot guarantee removal of every external copy. Your browser stores session and language/data-saver preferences; signing out ends the local signed-in experience.',
'Les demandes et nouvelles pi\u00e8ces jointes sont destin\u00e9es \u00e0 un examen autoris\u00e9, pas \u00e0 un fil public. Un contenu publi\u00e9 par un responsable autoris\u00e9 devient public et peut \u00eatre copi\u00e9 ou conserv\u00e9 ailleurs. Son retrait de CNM ne garantit pas l\u2019effacement de toutes les copies externes. Le navigateur conserve la session et les pr\u00e9f\u00e9rences de langue et de donn\u00e9es ; la d\u00e9connexion ferme la session locale.',
'Demann ak nouvo py\u00e8s ansanm yo se pou revizyon moun ki otorize, pa pou yon fil piblik. Kontni yon responsab otorize pibliye vin piblik, epi l\u00f2t moun ka kopye oswa kons\u00e8ve l. Retire l sou CNM pa garanti tout kopi ekst\u00e8n efase. Navigat\u00e8 ou sere sesyon ak preferans lang ak ekonomi done; dekonekte f\u00e8men sesyon lokal la.',
'Las consultas y los nuevos archivos adjuntos se destinan a revisi\u00f3n autorizada, no a un canal p\u00fablico. El material que publica una persona autorizada es p\u00fablico y puede copiarse o almacenarse fuera de CNM. Retirarlo no garantiza eliminar todas las copias externas. El navegador guarda sesi\u00f3n, idioma y ahorro de datos; cerrar sesi\u00f3n termina el acceso local.']},
{id:'requests',heading:['Privacy questions and requests','Questions et demandes de confidentialit\u00e9','Kesyon ak demann sou konfidansyalite','Preguntas y solicitudes de privacidad'],body:[
'Contact creolenetworkmedia@gmail.com to ask about access, correction or deletion of information you provided. CNM may need to verify that a request concerns your information. A fixed retention schedule and final rights-handling procedure have not yet been adopted in this draft. This notice does not promise immediate deletion from backups or from copies published outside CNM.',
'Contactez creolenetworkmedia@gmail.com pour une demande d\u2019acc\u00e8s, de correction ou de suppression des informations fournies. CNM peut devoir v\u00e9rifier qu\u2019elles vous concernent. Les dur\u00e9es de conservation et la proc\u00e9dure finale de traitement des droits ne sont pas encore adopt\u00e9es dans ce projet. Cette notice ne promet pas un effacement imm\u00e9diat des sauvegardes ni des copies hors CNM.',
'Kontakte creolenetworkmedia@gmail.com pou mande aks\u00e8, koreksyon oswa efasman enf\u00f2masyon ou te bay. CNM ka bezwen verifye demann lan kons\u00e8ne enf\u00f2masyon pa ou. Dire kons\u00e8vasyon ak pwosedi final pou trete dwa yo poko adopte nan bouyon sa a. Politik sa a pa pwom\u00e8t efasman imedyat nan kopi sekou oswa kopi ki pibliye dey\u00f2 CNM.',
'Contacta con creolenetworkmedia@gmail.com para solicitar acceso, correcci\u00f3n o eliminaci\u00f3n de tus datos. CNM puede necesitar verificar que la solicitud se refiere a tu informaci\u00f3n. Este borrador a\u00fan no adopta plazos de conservaci\u00f3n ni un procedimiento final de derechos. No promete una eliminaci\u00f3n inmediata de copias de seguridad ni de copias externas.']}
],
editorial:[
{id:'review',heading:['A submission is a proposal','Une contribution est une proposition','Yon kontribisyon se yon pwopozisyon','Un env\u00edo es una propuesta'],body:[
'CNM welcomes community story ideas, articles and relevant media for review. Sending material does not guarantee publication, payment or a response within a fixed time. An accepted submission still requires a separate publication decision by an authorized administrator.',
'CNM accueille les id\u00e9es, articles et m\u00e9dias communautaires pour examen. Un envoi ne garantit ni publication, ni r\u00e9mun\u00e9ration, ni r\u00e9ponse dans un d\u00e9lai fixe. Une contribution accept\u00e9e exige encore une d\u00e9cision de publication distincte par un administrateur autoris\u00e9.',
'CNM akeyi lide istwa, atik ak medya kominot\u00e8 pou revizyon. Voye yon kontni pa garanti piblikasyon, peman oswa repons nan yon del\u00e8 fiks. Menm l\u00e8 yon kontribisyon aksepte, yon admin otorize dwe pran yon desizyon apa pou pibliye l.',
'CNM recibe ideas, art\u00edculos y medios comunitarios para revisi\u00f3n. Enviarlos no garantiza publicaci\u00f3n, pago ni respuesta en un plazo fijo. Una contribuci\u00f3n aceptada a\u00fan requiere una decisi\u00f3n de publicaci\u00f3n separada de un administrador autorizado.']},
{id:'accuracy',heading:['Accuracy and attribution','Exactitude et attribution','Presizyon ak sous','Exactitud y atribuci\u00f3n'],body:[
'Distinguish verified facts from opinion. Identify sources, dates and relevant context. Do not fabricate quotes, identities, events or evidence. Credit original reporting and obtain permission where needed. CNM may request clarifications or decline unsupported material.',
'Distinguez les faits v\u00e9rifi\u00e9s des opinions. Identifiez sources, dates et contexte. N\u2019inventez ni citations, ni identit\u00e9s, ni \u00e9v\u00e9nements, ni preuves. Attribuez les informations originales et obtenez les autorisations n\u00e9cessaires. CNM peut demander des pr\u00e9cisions ou refuser un contenu insuffisamment \u00e9tay\u00e9.',
'Distenge reyalite ki verifye ak opinyon. Idantifye sous, dat ak kont\u00e8ks ki enp\u00f2tan. Pa envante sitasyon, idantite, ev\u00e8nman oswa pr\u00e8v. Bay kredi pou rep\u00f2taj orijinal epi jwenn p\u00e8misyon kote sa neses\u00e8. CNM ka mande detay oswa refize kontni ki pa gen sip\u00f2.',
'Distingue los hechos verificados de las opiniones. Identifica fuentes, fechas y contexto. No inventes citas, identidades, eventos o pruebas. Atribuye la informaci\u00f3n original y consigue los permisos necesarios. CNM puede pedir aclaraciones o rechazar material sin respaldo.']},
{id:'media',heading:['Photographs and video','Photographies et vid\u00e9os','Foto ak videyo','Fotograf\u00edas y video'],body:[
'Provide photographs you own or are authorized to submit, with accurate captions, credits and image descriptions. Disclose significant alterations and do not present fabricated imagery as documentary reporting. Link to a supported public video rather than pasting embed code. A link is not proof that you own the underlying material.',
'Fournissez des photographies que vous poss\u00e9dez ou pouvez soumettre, avec l\u00e9gendes, cr\u00e9dits et descriptions exacts. Signalez les modifications importantes et ne pr\u00e9sentez pas une image fabriqu\u00e9e comme un document de reportage. Utilisez un lien vid\u00e9o public pris en charge plut\u00f4t qu\u2019un code d\u2019int\u00e9gration. Un lien ne prouve pas la propri\u00e9t\u00e9 du contenu.',
'Bay foto ou posede oswa ou gen dwa soum\u00e8t, ak lejann, kredi ak deskripsyon ki k\u00f2r\u00e8k. Di si ou f\u00e8 gwo modifikasyon epi pa prezante imaj fabrike k\u00f2m pr\u00e8v rep\u00f2taj. Mete yon lyen videyo piblik ki sip\u00f2te olye k\u00f2d entegrasyon. Yon lyen pa prouve ou posede kontni an.',
'Proporciona fotos propias o autorizadas, con pies, cr\u00e9ditos y descripciones correctos. Declara las alteraciones importantes y no presentes im\u00e1genes fabricadas como reportaje documental. Usa un enlace p\u00fablico compatible en lugar de c\u00f3digo de inserci\u00f3n. Un enlace no prueba que seas propietario del contenido.']},
{id:'respect',heading:['Respect, safety and privacy','Respect, s\u00e9curit\u00e9 et vie priv\u00e9e','Resp\u00e8, sekirite ak lavi prive','Respeto, seguridad y privacidad'],body:[
'Do not submit threats, harassment, discriminatory abuse, unlawful material or private personal information without a legitimate basis and appropriate permission. Be especially careful with images and identifying information involving children or vulnerable people. CNM may withhold material pending further review.',
'Ne soumettez ni menaces, ni harc\u00e8lement, ni abus discriminatoires, ni contenu illicite, ni informations priv\u00e9es sans justification l\u00e9gitime et autorisation appropri\u00e9e. Soyez particuli\u00e8rement attentif aux images et informations concernant des enfants ou des personnes vuln\u00e9rables. CNM peut suspendre un contenu pour examen.',
'Pa voye menas, arasman, abi diskriminatwa, kontni ilegal oswa enf\u00f2masyon prive san yon rezon lejitim ak p\u00e8misyon ki apwopriye. F\u00e8 anpil atansyon ak foto ak enf\u00f2masyon ki idantifye timoun oswa moun vilnerab. CNM ka tann plis revizyon anvan li itilize yon kontni.',
'No env\u00edes amenazas, acoso, abuso discriminatorio, material ilegal ni datos privados sin una base leg\u00edtima y el permiso adecuado. Ten especial cuidado con im\u00e1genes y datos identificativos de menores o personas vulnerables. CNM puede retener material para una revisi\u00f3n adicional.']},
{id:'promotion',heading:['Paid content and independence','Contenus payants et ind\u00e9pendance','Kontni peye ak endepandans','Contenido pagado e independencia'],body:[
'Commercial promotion should be clearly identified on the article entry and the article itself, in the language being shown. A sponsorship inquiry does not buy editorial approval. Any paid-content arrangement and its disclosure must be agreed separately from ordinary news submissions.',
'Une promotion commerciale doit \u00eatre clairement identifi\u00e9e sur l\u2019aper\u00e7u et dans l\u2019article, dans la langue affich\u00e9e. Une demande de partenariat n\u2019ach\u00e8te pas une approbation \u00e9ditoriale. Tout accord de contenu payant et ses mentions doivent \u00eatre convenus s\u00e9par\u00e9ment des contributions d\u2019actualit\u00e9 ordinaires.',
'Piblisite kom\u00e8syal dwe byen make sou ap\u00e8si atik la ak nan atik la, nan lang yo montre a. Yon demann patn\u00e8 pa achte apwobasyon redaksyon. Nenp\u00f2t ak\u00f2 kontni peye ak mansyon li yo dwe f\u00e8t apa de kontribisyon nouv\u00e8l n\u00f2mal yo.',
'La promoci\u00f3n comercial debe identificarse claramente en la entrada del art\u00edculo y en su contenido, en el idioma mostrado. Una consulta de patrocinio no compra aprobaci\u00f3n editorial. Cualquier acuerdo de contenido pagado y su identificaci\u00f3n deben pactarse por separado de los env\u00edos de noticias.']},
{id:'corrections',heading:['Corrections and permissions','Corrections et autorisations','Koreksyon ak p\u00e8misyon','Correcciones y permisos'],body:[
'To report an error or rights concern, use Contact and include the article URL, the specific concern and any supporting source. Do not upload confidential identity documents. Before publishing accepted work, CNM should confirm credits, publication permission and substantial changes with the contributor. The final editorial policy remains subject to station review.',
'Pour signaler une erreur ou un probl\u00e8me de droits, utilisez Contact avec le lien de l\u2019article, le point pr\u00e9cis et une source utile. N\u2019envoyez pas de documents d\u2019identit\u00e9 confidentiels. Avant publication, CNM doit confirmer les cr\u00e9dits, l\u2019autorisation et les modifications importantes avec le contributeur. La politique finale reste soumise \u00e0 la validation de la station.',
'Pou rap\u00f2te yon er\u00e8 oswa pwobl\u00e8m dwa, itilize Kontak epi mete lyen atik la, pwobl\u00e8m presi a ak sous ki itil. Pa voye dokiman idantite konfidansy\u00e8l. Anvan piblikasyon, CNM dwe konfime kredi, p\u00e8misyon ak gwo chanjman ak moun ki kontribye a. Politik redaksyon final la rete pou estasyon an valide.',
'Para informar de un error o un problema de derechos, usa Contacto e incluye la URL, la cuesti\u00f3n concreta y una fuente de apoyo. No env\u00edes documentos de identidad confidenciales. Antes de publicar, CNM debe confirmar los cr\u00e9ditos, el permiso y los cambios importantes con el colaborador. La pol\u00edtica final sigue sujeta a revisi\u00f3n de la emisora.']}
]}
